### ISSUE TITLE
Grid in a EditForm

### ISSUE THREAD

**Issue by DanielReif** [DevExpress/Blazor#102]
Hello,

i try to use a Grid in a EditForm. But when i take it, i get a NullException Error.

`System.ArgumentNullException: Value cannot be null. (Parameter 'accessor')
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at DevExpress.Blazor.Internal.DxEditorBase`2.CreateFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldClass()
   at DevExpress.Blazor.Base.DxTextBoxBase.get_MainCssClass()
   at DevExpress.Blazor.DxTextBox.BuildRenderTree(RenderTreeBuilder __builder)
   at DevExpress.Blazor.Base.DxComponentBase.BuildRenderTreeCore(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.Blazor.Base.DxDecoratedComponent.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
`

Here is a simple example for it. The first grid works, but the second one throw the error when i click on "new" or "edit". I know i have no validation or something else in the editform. I only want to show that the error occours when i move the grid in a editform.
https://pastebin.com/eyV4ukD2

Kind regards

**Comment by zabelin-vladimir** [comment]
Hello @DanielReif 

Would you please clarify the version of our NuGet package which you installed? I tested your code with the 19.2.4 version of our controls and it works properly.

**Comment by DanielReif** [comment]
I use 19.2.4. Fresh installed in the demo project. Do you click the new/edit button in the second grid?

**Comment by zabelin-vladimir** [comment]
Hello @DanielReif

Thank you for your clarification. This behavior is expected. We have discussed it and a possible solution in [this ticket](https://supportcenter.devexpress.com/ticket/details/t847509). Please try Marina's approach from there and let me know your results.
