### ISSUE TITLE
NullReferenceException in short form of DxFormLayoutItem

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#128]
When using `DxFormLayoutItem` in the following short-form:

```
<DxFormLayout Data="@Model" ItemUpdating="@((fieldName, newValue) => OnItemUpdating(fieldName, newValue))" CaptionPosition=@CaptionPosition.Vertical>
                    <DxFormLayoutTabPages>
                        <DxFormLayoutTabPage Caption="Eigenschaften">

                            <DxFormLayoutItem Field="@nameof(IntranetUser.UserName)" Caption="Login *" ColSpanMd="6" />
```

The following error is raised:

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at DevExpress.Blazor.Internal.DataBindHelper.GetFieldValueInfo[T](T dataItem, String fieldName, Object& value, Type& type)
   at DevExpress.Blazor.Base.DxFormLayoutBase.GetItemValue(DxFormLayoutItemBase layoutItem, Object data, Object& value, Type& type)
   at DevExpress.Blazor.Base.DxFormLayoutBase.GetLayoutItemTemplate(DxFormLayoutItemBase layoutItem)
   at DevExpress.Blazor.Base.DxFormLayoutBase.GetLayoutItemTemplate(IFormLayoutItem layoutItem)
   at DevExpress.Blazor.Base.DxFormLayoutBase.DevExpress.Blazor.FormLayout.Internal.IFormLayoutBase.GetLayoutItemTemplate(IFormLayoutItem layoutItem)
   at DevExpress.Blazor.FormLayout.Internal.FormLayoutTabPageRenderBase.GetLayoutItemTemplate(IFormLayoutItem layoutItem)
   at DevExpress.Blazor.FormLayout.Internal.FormLayoutLevelRenderer.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

But this used to work before. What's the problem here?

**Comment by sven5** [comment]
Hi team,

I must have missed something. This is clearly a bug. 
It's working when the value of `UserName` is not-null - otherwise the exception is thrown.
Please look into this. 
Thanks

**Comment by sven5** [comment]
it seems that `DevExpress.Blazor.Internal.DataBindHelper.GetFieldValueInfo` cannot deal with null values. :hushed:

**Comment by zabelin-vladimir** [comment]
Hello @sven5

Thank you for your report. I reproduced this behavior on my side. We will research it in the context of the following ticket in our support center: [FormLayout for Blazor - The NullReference exception occurs if DxFormLayoutItem is bound to a string field with a null value](https://supportcenter.devexpress.com/ticket/details/t894105/formlayout-for-blazor-the-nullreference-exception-occurs-if-dxformlayoutitem-is-bound-to).

**Comment by rgonzalezr** [comment]
Is there a workaround for this bug? Is there an alternate way of data-binding a field (that has null values) to a DxFormLayoutItem? Thanks.

**Comment by sven5** [comment]
Hi @rgonzalezr 
Yes just use the verbose form of creating a FormLayout as shown in the examples here: https://demos.devexpress.com/blazor/FormLayout

**Comment by zabelin-vladimir** [comment]
Hello all,

We have fixed the issue. The fix will be included in our next update, which will be available via the DevExpress NuGet server.
