### ISSUE TITLE
Cascading DxComboBox: Allow initial null value

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#70]
Hi DevExpress Team,

when using two cascading ComboBoxes one has to use the `SelectedItem `and `SelectedItemChanged`.
However, the `SelectedItem` parameter cannot be null, it must be preselected with one of the list's values. Otherwise the component fails with "Value cannot be null" exceptions. 
From the user pespective and validation purposes this is not ideal. 

It would be better to allow initial null values for the first ComboBox, which means the user **has to explicitly** select an item.

Thanks
Sven

**Edit Full Exception Stack Trace:**
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'accessor')
System.ArgumentNullException: Value cannot be null. (Parameter 'accessor')
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at DevExpress.Blazor.Internal.DxEditorBase`2.CreateFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldClass()
   at DevExpress.Blazor.DxComboBox`1.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'Q7vdQ0VHITiH23Ycynz5fCRfkzGqv4i4paJf9ruyMZA'.

**Comment by sven5** [comment]
@SergeySeleznyov 
Just one addition: it's possible that this issue interfers with #71

**Comment by SergeySeleznyov** [comment]
Yes, they are related.

The callstack you sent looks to mean: Value of expression (SelectedItemExpression) cannot be null.
If you initialize the SelectedItemExpression then this error will more likely disappear.

**Comment by sven5** [comment]
You're right. We can close this.
