### ISSUE TITLE
Problem with cascading DxComboBoxes in EditFormTemplate of DxDataGrid

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#71]
Hi DevExpress Team.

it seems that there is an issue when using two cascading comboboxes inside an `EditFormTemplate `of the `DxDataGrid`.  I always get the following exception:

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'GNieSDbXCYHZRULN6gzNWNvRck_tY3cC_L2s7M_P2e8'.
System.ArgumentNullException: Value cannot be null. (Parameter 'accessor')
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at DevExpress.Blazor.Internal.DxEditorBase`2.CreateFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldIdentifier()
   at DevExpress.Blazor.Internal.DxEditorBase`2.get_EditFormFieldClass()
   at DevExpress.Blazor.DxComboBox`1.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by sven5** [comment]
This seems to be a general issue regarding the `DxComboBox` inside an `EditForm` when not using two-way binding.  
The workaround is to set the `SelectedItemExpression` manually. But I think this is neither recommended nor intended.

Regards
Sven

**Comment by SergeySeleznyov** [comment]
Hi Sven,

You are right, the both the issues you have just reported look to be about the same topic.
If you use two-way binding syntax for the component, then the Blazor initializes the Expression by itself. But if you split the binding into a one-way property bind + Changed event handling, then you have to initialize the Expression.

You may also refer to the same ticket here: [T831079](https://supportcenter.devexpress.com/ticket/details/T831079)

Please let us know whether you need any further assistance.

**Comment by sven5** [comment]
Example:

**doesn't work**
```
<DxComboBox Data="@Tenants"
        TextFieldName="Name"
        SelectedItem="@EditItem.Tenant" 
        SelectedItemChanged="@OnTenantChanged">
</DxComboBox>
```

**works**
<DxComboBox Data="@Tenants"
        TextFieldName="Name"
        SelectedItem="@EditItem.Tenant" 
        SelectedItemChanged="@OnTenantChanged"
        SelectedItemExpression="@(() => EditItem.Tenant)">
</DxComboBox>

**Comment by SergeySeleznyov** [comment]
Hi Sven,

Would you please clarify whether you need any assistance with this issue?

**Comment by sven5** [comment]
No, thanks. I was able to workaround with using the `SelectedItemExpression`.
