### ISSUE TITLE
DxDataGrid:  New throws exception

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#9]
Display and Editing all work well with DxDataGrid, when click New, it throws below exception, Is there any way to get more information?

ystem.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at Blazor.STP.ServerSide.Pages.Dynamic.<>c__DisplayClass0_2.<BuildRenderTree>b__7(RenderTreeBuilder builder3)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.Blazor.DxDataGridRow`1.<>c__DisplayClass0_0.<BuildRenderTree>b__3(RenderTreeBuilder builder3)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.Blazor.FormLayout.Internal.FormLayoutItemRender.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 7317.7419ms 101

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc,
 
If running with debug does not show the code/markup line that causes the exception, I would recommend repeating the steps without some columns.
 
If it does not help, post a simple working example here, I will try to help.

**Comment by SergeySeleznyov** [comment]
We have received the following ticket today:
[NullReferenceException occurs after canceling new row editing](https://www.devexpress.com/Support/Center/Question/Details/T745260).
 
It may be related to the scenario you described.

**Comment by goldmannyc** [comment]
Thanks for looking into this,  the application dynamically constructs the database entities and passes it to the razor page for Crud operations.

The exception happens when using the Boolean Template, the display and edit of the grid work well, when click New,  it throws exception.  

It was running in debugger, the exception throws after passing the DisplayTemplate portion of the code below.

`protected dynamic[] Items; // array of dynamic populated at runtime to represent database entities`
`protected IEnumerable<PropertyInfo> Columns;  // PropertyInfo for each property of the entity //populated at rumtime`
`...`
```
<DxDataGrid Data=@Items
                PageSize=@PageSize
                RowRemoving=@((dataItem) => OnRowRemoving(dataItem))
                RowUpdating=@((updatingDataItem, newValues) => OnRowUpdating(updatingDataItem, newValues))
                RowInserting=@((newValues) => OnRowInserting(newValues))>
        <DxDataGridCommandColumn Width="150px"></DxDataGridCommandColumn>
        @{
            foreach (var col in @Columns)
            {
                var underlyingType = Nullable.GetUnderlyingType(col.PropertyType);
                var type = underlyingType ?? col.PropertyType;
                if (type == typeof(Boolean))
                {
                    {<DxDataGridColumn Field=@col.Name >
                        <DisplayTemplate>
                            @{
                                var id = Guid.NewGuid().ToString();
                                bool value = (bool)(col.GetValue(context, null) ?? false);
                                if (value)
                                {
                                    <label class="form-check-label text-success" for=@id>True</label>
                                }
                                else
                                {
                                    <label class="form-check-label text-danger" for=@id>False</label>
                                }
                            }
                        </DisplayTemplate>
                        <EditTemplate>
                            <DxComboBox Data=@(new List<string>() { "True", "False"})
                                        SelectedItem=@( ((CellEditContext)context)?.CellValue == null ? "False"
                                            : ((bool)((CellEditContext)context)?.CellValue == true ? "True" : "False" ) )
                                        SelectedItemChanged=@(newCellValue => ((CellEditContext)context)?.OnChanged(newCellValue == "True"))>
                            </DxComboBox>
                        </EditTemplate>
                    </DxDataGridColumn>}
                }
                @*else if (type == typeof(DateTime))
                {
                    {<DxDataGridDateEditColumn Field=@col.Name>
                            <EditTemplate>
                                <DxDateEdit NullText = "2001-01-01" ></DxDateEdit>
                            </EditTemplate>
                    </DxDataGridDateEditColumn>}
                }*@    
                else if (type != typeof(Boolean))
                {
                    {<DxDataGridColumn Field=@col.Name></DxDataGridColumn>}
                }
            }

        }
    </DxDataGrid>
```



```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview5-27626-15\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer: Warning: Unhandled exception rendering component: Unable to cast object of type 'System.String' to type 'System.Boolean'.

System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at Blazor.STP.ServerSide.Pages.Dynamic.<>c__DisplayClass0_2.<BuildRenderTree>b__7(RenderTreeBuilder builder3)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.Blazor.DxDataGridRow`1.<>c__DisplayClass0_0.<BuildRenderTree>b__3(RenderTreeBuilder builder3)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.Blazor.FormLayout.Internal.FormLayoutItemRender.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.ComponentHub: Warning: Unhandled Server-Side exception

```

**Comment by SergeySeleznyov** [comment]
Would you please take a look at the following sample? Does it meet your requirement?
Please take note of the approach with the "@{...}" code block in the template. I found it useful for some issue catching.
 
```
@page "/test"
@using System.Reflection

<DxDataGrid Data=@Items
            PageSize=@PageSize
            RowRemoving=@((dataItem) => OnRowRemoving(dataItem))
            RowUpdating=@((updatingDataItem, newValues) => OnRowUpdating(updatingDataItem, newValues))
            RowInserting=@((newValues) => OnRowInserting(newValues))>
    <DxDataGridCommandColumn Width="150px"></DxDataGridCommandColumn>
    @{
            foreach (var col in @Columns)
            {
                var underlyingType = Nullable.GetUnderlyingType(col.PropertyType);
                var type = underlyingType ?? col.PropertyType;
                if (type == typeof(Boolean))
                {
                    {<DxDataGridColumn Field=@col.Name>
            <DisplayTemplate>
                @{
                                var id = Guid.NewGuid().ToString();
                                bool value = (bool)(col.GetValue(context, null) ?? false);
                                if (value)
                                {
                    <label class="form-check-label text-success" for=@id>True</label>
                                }
                                else
                                {
                    <label class="form-check-label text-danger" for=@id>False</label>
                                }
                }
            </DisplayTemplate>
            <EditTemplate>
                @{
                    var cellEditContext = (CellEditContext)context;
                    string comboBoxValue = Boolean.Equals(cellEditContext?.CellValue, true) ? "True" : "False";
                }
                <DxComboBox Data=@(new List<string>() { "True", "False"})
                    SelectedItem=@(comboBoxValue)
                    SelectedItemChanged=@(newCellValue => cellEditContext?.OnChanged(newCellValue == "True"))>
        </DxComboBox>
            </EditTemplate>
        </DxDataGridColumn>}
                }
        @*else if (type == typeof(DateTime))
            {
                {<DxDataGridDateEditColumn Field=@col.Name>
                        <EditTemplate>
                            <DxDateEdit NullText = "2001-01-01" ></DxDateEdit>
                        </EditTemplate>
                </DxDataGridDateEditColumn>}
            }*@
                else if (type != typeof(Boolean))
                {
                    {<DxDataGridColumn Field=@col.Name></DxDataGridColumn>}
                }
            }

    }
</DxDataGrid>
@functions {
    int PageSize = 2;
    class MyDataItem {
        public string Text { get; set; }
        public bool Flag { get; set; }
    }

    // array of dynamic populated at runtime to represent database entities
    dynamic[] Items = new MyDataItem[] {
        new MyDataItem() { Text = "Text 1", Flag = true },
        new MyDataItem() { Text = "Text 2", Flag = false }
    };

    // PropertyInfo for each property of the entity //populated at rumtime
    IEnumerable<PropertyInfo> Columns = new List<PropertyInfo> { 
         typeof(MyDataItem).GetProperty(nameof(MyDataItem.Text)),
         typeof(MyDataItem).GetProperty(nameof(MyDataItem.Flag))
    }; 

    void OnRowRemoving(MyDataItem dataItem)
    {
        
    }
    void OnRowUpdating(MyDataItem dataItem, Dictionary<string, object> newValue)
    {
        
    }
    void OnRowInserting(Dictionary<string, object> newValue)
    {
        
    }
}
```

**Comment by goldmannyc** [comment]
Thanks, this worked out perfectly.
